/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    iva: bigint;
    categoryId: bigint;
    updatedDate: bigint;
    name: string;
    createdDate: bigint;
    description: string;
    stock: bigint;
    barcode: string;
    profitMargin: bigint;
    basePrice: number;
}
export interface AnalyticsData {
    archivedOrders: Array<Order>;
    activeOrders: Array<Order>;
}
export interface PaginatedAdjustments {
    totalCount: bigint;
    adjustments: Array<InventoryAdjustment>;
}
export interface OrdersImportResult {
    resultDetails: Array<string>;
    nextOrderId: bigint;
    errors: Array<string>;
    importedCount: bigint;
    updatedCount: bigint;
    errorCount: bigint;
    skippedCount: bigint;
}
export interface LegacyProductImportDTO {
    categoryName: string;
    name: string;
    description: string;
    stock: bigint;
    barcode: string;
    salePrice: number;
}
export interface AnalyticsFilters {
    categoryFilter?: bigint;
    paymentMethodFilter?: string;
    toDate: bigint;
    includeArchived: boolean;
    fromDate: bigint;
}
export interface AdjustmentResult {
    adjustment: InventoryAdjustment;
    warnings: Array<string>;
    success: boolean;
}
export interface OrderItem {
    categoryName: string;
    ivaRate: bigint;
    productName: string;
    quantity: bigint;
    salePrice: number;
    totalPrice: number;
    profitMargin: bigint;
    basePrice: number;
    productBarcode: string;
    updatedStock: bigint;
    originalStock: bigint;
}
export interface CreateOrderResponse {
    order: Order;
    warnings: Array<string>;
    success: boolean;
}
export interface AdjustmentFilters {
    reasonFilter?: string;
    adjustmentTypeFilter?: string;
    toDate?: bigint;
    fromDate?: bigint;
    productSearch?: string;
}
export interface ReturnOrderDTO {
    refundAmount: number;
    originalOrderId: string;
    items: Array<ReturnItem>;
    adminNotes: string;
    originalOrderNumber: string;
    returnType: Variant_full_cancellation_partial;
    otherReason?: string;
    reason: Variant_other_defective_incorrect_change_of_mind;
}
export interface ImportResult {
    errors: Array<string>;
    successCount: bigint;
    errorCount: bigint;
}
export interface AdjustmentDTO {
    dateEffective: bigint;
    quantity: bigint;
    adjustmentType: Variant_decrease_increase;
    adminNotes: string;
    productBarcode: string;
    reason: Variant_theft_broken_expired_lost_count_error;
}
export interface ArchiveResult {
    archivedCount: bigint;
    archivedIds: Array<string>;
}
export interface PaginatedReturns {
    totalCount: bigint;
    returns: Array<ReturnOrder>;
}
export interface ReturnOrder {
    refundAmount: number;
    status: Variant_pending_rejected_processed;
    originalOrderId: string;
    stockRestored: boolean;
    createdDate: bigint;
    items: Array<ReturnItem>;
    processedDate?: bigint;
    statusChangeNotes?: string;
    returnNumber: string;
    adminNotes: string;
    originalOrderNumber: string;
    returnType: Variant_full_cancellation_partial;
    returnId: bigint;
    otherReason?: string;
    reason: Variant_other_defective_incorrect_change_of_mind;
}
export interface ReceiptData {
    order?: Order;
    receiptType: Variant_order_returnOrder;
    returnOrder?: ReturnOrder;
    storeInfo: {
        name: string;
        whatsapp: string;
        address: string;
        phone: string;
    };
    timestamp: bigint;
}
export interface OrderImportConfig {
    targetDataset: string;
    preserveTimestamps: boolean;
    updateStock: boolean;
    conflictResolution: string;
}
export interface LegacyCategoryImportDTO {
    defaultIVA: bigint;
    order: bigint;
    name: string;
    defaultProfitMargin: bigint;
}
export interface AdjustmentAnalytics {
    totalValueLost: number;
    mostAffectedProduct?: {
        name: string;
        amount: bigint;
    };
    totalAdjustments: bigint;
    primaryReason?: string;
}
export interface TaxBreakdownExportDTO {
    taxableAmount: number;
    ivaRate: bigint;
    baseAmount: number;
    taxAmount: number;
}
export interface ProductWithCategory {
    categoryName: string;
    product: Product;
}
export interface ProductExportDTO {
    iva: bigint;
    categoryId: bigint;
    updatedDate: string;
    name: string;
    createdDate: string;
    description: string;
    stock: bigint;
    barcode: string;
    salePrice: number;
    profitMargin: bigint;
    basePrice: number;
}
export interface OrderImportDTO {
    status: string;
    customerNotes: string;
    paymentMethod: string;
    discountAmount: number;
    orderId: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: bigint;
    taxBreakdown?: Array<TaxBreakdownImportDTO>;
    items: Array<OrderItemImportDTO>;
    orderNumber: string;
}
export interface CategoriesImportResult {
    errors: Array<string>;
    importedCount: bigint;
    errorCount: bigint;
    skippedCount: bigint;
}
export interface Category {
    id: bigint;
    defaultIVA: bigint;
    order: bigint;
    name: string;
    defaultProfitMargin: bigint;
}
export interface ArchivedOrder {
    order: Order;
    archiveDate: bigint;
}
export interface ProductSearchResult {
    iva: bigint;
    categoryName: string;
    name: string;
    stock: bigint;
    barcode: string;
    profitMargin: bigint;
    basePrice: number;
}
export interface PaginatedArchivedOrders {
    orders: Array<ArchivedOrder>;
    totalCount: bigint;
}
export interface PaginatedOrders {
    orders: Array<Order>;
    totalCount: bigint;
}
export interface ProductsImportResult {
    errors: Array<string>;
    importedCount: bigint;
    errorCount: bigint;
    skippedCount: bigint;
}
export interface ProductsExportResult {
    totalCount: bigint;
    products: Array<ProductExportDTO>;
    exportTimestamp: string;
}
export interface OrderItemExportDTO {
    categoryName: string;
    ivaRate: bigint;
    productName: string;
    quantity: bigint;
    salePrice: number;
    totalPrice: number;
    profitMargin: bigint;
    basePrice: number;
    productBarcode: string;
}
export interface TaxBreakdown {
    taxableAmount: number;
    ivaRate: bigint;
    baseAmount: number;
    taxAmount: number;
}
export interface StoreDetails {
    taxId?: string;
    lastUpdated: bigint;
    whatsapp: string;
    email?: string;
    website?: string;
    address: string;
    storeName: string;
    phone: string;
}
export interface CategoriesExportResult {
    categories: Array<CategoryExportDTO>;
    totalCount: bigint;
    exportTimestamp: string;
}
export interface ProductImportDTO {
    iva: bigint;
    categoryId: bigint;
    updatedDate: bigint;
    name: string;
    createdDate: bigint;
    description: string;
    stock: bigint;
    barcode: string;
    profitMargin: bigint;
    basePrice: number;
}
export interface Order {
    customerName?: string;
    status: Variant_valid_invalid;
    customerNotes: string;
    paymentMethod: Variant_card_cash_transfer;
    discountAmount: number;
    orderId: string;
    customerTaxId?: string;
    invoiceType: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: bigint;
    taxBreakdown?: Array<TaxBreakdown>;
    items: Array<OrderItem>;
    orderNumber: string;
}
export interface ReturnItem {
    returnedQuantity: bigint;
    categoryName: string;
    stockRestored: boolean;
    originalQuantity: bigint;
    productName: string;
    refundPerUnit: number;
    totalRefund: number;
    productBarcode: string;
}
export interface CategoryImportDTO {
    categoryId: bigint;
    defaultIVA: bigint;
    order: bigint;
    name: string;
    defaultProfitMargin: bigint;
}
export interface OrdersExportResult {
    orders: Array<OrderExportDTO>;
    totalCount: bigint;
    exportTimestamp: string;
}
export interface OrderExportDTO {
    status: string;
    customerNotes: string;
    paymentMethod: string;
    discountAmount: number;
    orderId: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: string;
    taxBreakdown?: Array<TaxBreakdownExportDTO>;
    items: Array<OrderItemExportDTO>;
    orderNumber: string;
}
export interface ArchivePreviewResult {
    orderCount: bigint;
}
export interface TaxBreakdownImportDTO {
    taxableAmount: number;
    ivaRate: bigint;
    baseAmount: number;
    taxAmount: number;
}
export interface StatusResult {
    message: string;
    success: boolean;
}
export interface InventoryAdjustment {
    dateEffective: bigint;
    productName: string;
    adminUserId: string;
    timestamp: bigint;
    newStock: bigint;
    previousStock: bigint;
    quantity: bigint;
    adjustmentId: bigint;
    adjustmentType: Variant_decrease_increase;
    adminNotes: string;
    productBarcode: string;
    reason: Variant_theft_broken_expired_lost_count_error;
}
export interface PaginatedProducts {
    totalCount: bigint;
    products: Array<ProductWithCategory>;
}
export interface CreateOrderRequest {
    customerName?: string;
    customerNotes: string;
    paymentMethod: Variant_card_cash_transfer;
    discountAmount: number;
    customerTaxId?: string;
    invoiceType: string;
    printReceipt: boolean;
    taxBreakdown?: Array<TaxBreakdown>;
    items: Array<OrderItem>;
}
export interface CategoryExportDTO {
    id: bigint;
    defaultIVA: bigint;
    order: bigint;
    name: string;
    defaultProfitMargin: bigint;
    productCount: bigint;
}
export interface ReturnResult {
    returnOrder: ReturnOrder;
    warnings: Array<string>;
    success: boolean;
}
export interface UserProfile {
    name: string;
}
export interface OrderItemImportDTO {
    categoryName: string;
    ivaRate: bigint;
    productName: string;
    quantity: bigint;
    salePrice: number;
    totalPrice: number;
    profitMargin: bigint;
    basePrice: number;
    productBarcode: string;
    updatedStock: bigint;
    originalStock: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_card_cash_transfer {
    card = "card",
    cash = "cash",
    transfer = "transfer"
}
export enum Variant_decrease_increase {
    decrease = "decrease",
    increase = "increase"
}
export enum Variant_full_cancellation_partial {
    full = "full",
    cancellation = "cancellation",
    partial = "partial"
}
export enum Variant_order_returnOrder {
    order = "order",
    returnOrder = "returnOrder"
}
export enum Variant_other_defective_incorrect_change_of_mind {
    other = "other",
    defective = "defective",
    incorrect = "incorrect",
    change_of_mind = "change_of_mind"
}
export enum Variant_pending_rejected_processed {
    pending = "pending",
    rejected = "rejected",
    processed = "processed"
}
export enum Variant_theft_broken_expired_lost_count_error {
    theft = "theft",
    broken = "broken",
    expired = "expired",
    lost = "lost",
    count = "count",
    error = "error"
}
export enum Variant_valid_invalid {
    valid = "valid",
    invalid = "invalid"
}
export interface backendInterface {
    addCategory(name: string, order: bigint, defaultIVA: bigint, defaultProfitMargin: bigint): Promise<bigint>;
    addProduct(product: Product): Promise<void>;
    archiveOrders(dateFrom: bigint, dateTo: bigint): Promise<ArchiveResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignCallerUserRoleByText(principalId: string, role: UserRole): Promise<void>;
    bulkUpdateCategories(updates: Array<[bigint, bigint | null, bigint | null]>): Promise<void>;
    bulkUpdateProductsByCategory(categoryId: bigint, newIVA: bigint, newProfitMargin: bigint): Promise<void>;
    createInventoryAdjustment(adjustment: AdjustmentDTO): Promise<AdjustmentResult>;
    createOrder(request: CreateOrderRequest): Promise<CreateOrderResponse>;
    createReturn(returnData: ReturnOrderDTO): Promise<ReturnResult>;
    deleteCategory(id: bigint, confirmPassword: string): Promise<void>;
    deleteProduct(barcode: string, confirmPassword: string): Promise<void>;
    exportCategories(): Promise<CategoriesExportResult>;
    exportOrders(fromDate: bigint | null, toDate: bigint | null, statusFilter: string | null, paymentMethodFilter: string | null): Promise<OrdersExportResult>;
    exportProducts(categoryFilter: bigint | null, minStock: bigint | null, maxStock: bigint | null, fromDate: bigint | null, toDate: bigint | null): Promise<ProductsExportResult>;
    generateReturnReceipt(returnId: bigint): Promise<ReceiptData | null>;
    getArchivePreview(dateFrom: bigint, dateTo: bigint): Promise<ArchivePreviewResult>;
    getArchivedOrderDetails(orderId: string): Promise<Order | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getInventoryAdjustmentAnalytics(filters: AnalyticsFilters): Promise<AdjustmentAnalytics>;
    getOrder(orderNumber: string): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getPaginatedAdjustments(pageNumber: bigint, pageSize: bigint, filters: AdjustmentFilters): Promise<PaginatedAdjustments>;
    getPaginatedArchivedOrders(pageNumber: bigint, pageSize: bigint, searchTerm: string, searchMode: string, fromDate: bigint | null, toDate: bigint | null): Promise<PaginatedArchivedOrders>;
    getPaginatedOrders(pageNumber: bigint, pageSize: bigint, searchTerm: string, searchMode: string, fromDate: bigint | null, toDate: bigint | null, invoiceTypeFilter: string | null): Promise<PaginatedOrders>;
    getPaginatedProducts(pageNumber: bigint, pageSize: bigint, searchTerm: string, searchMode: string, categoryFilter: bigint, stockFilter: bigint | null, ivaFilter: bigint | null): Promise<PaginatedProducts>;
    getPaginatedReturns(pageNumber: bigint, pageSize: bigint, searchTerm: string, searchMode: string, typeFilter: string, statusFilter: string, reasonFilter: string, fromDate: bigint | null, toDate: bigint | null, originalOrderNumber: string | null): Promise<PaginatedReturns>;
    getProduct(barcode: string): Promise<Product | null>;
    getReturnDetails(returnId: bigint): Promise<ReturnOrder | null>;
    getSalesAnalyticsData(filters: AnalyticsFilters): Promise<AnalyticsData>;
    getStoreDetails(): Promise<StoreDetails>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importCategories(categoriesToImport: Array<CategoryImportDTO>): Promise<CategoriesImportResult>;
    importLegacyCategories(categoriesToImport: Array<LegacyCategoryImportDTO>): Promise<ImportResult>;
    importLegacyProducts(productsToImport: Array<LegacyProductImportDTO>): Promise<ImportResult>;
    importOrders(ordersToImport: Array<OrderImportDTO>, config: OrderImportConfig): Promise<OrdersImportResult>;
    importProducts(productsToImport: Array<ProductImportDTO>): Promise<ProductsImportResult>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isUserAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProductsForCheckout(searchTerm: string, searchMode: string, limit: bigint): Promise<Array<ProductSearchResult>>;
    updateCategory(id: bigint, name: string, order: bigint, defaultIVA: bigint, defaultProfitMargin: bigint): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateReturnStatus(returnId: bigint, newStatus: Variant_pending_rejected_processed, adminNotes: string | null): Promise<StatusResult>;
    updateStoreDetails(details: StoreDetails): Promise<{
        message: string;
        success: boolean;
    }>;
}
import type { AdjustmentAnalytics as _AdjustmentAnalytics, AdjustmentDTO as _AdjustmentDTO, AdjustmentFilters as _AdjustmentFilters, AdjustmentResult as _AdjustmentResult, AnalyticsData as _AnalyticsData, AnalyticsFilters as _AnalyticsFilters, ArchivedOrder as _ArchivedOrder, CreateOrderRequest as _CreateOrderRequest, CreateOrderResponse as _CreateOrderResponse, InventoryAdjustment as _InventoryAdjustment, Order as _Order, OrderExportDTO as _OrderExportDTO, OrderImportDTO as _OrderImportDTO, OrderItem as _OrderItem, OrderItemExportDTO as _OrderItemExportDTO, OrderItemImportDTO as _OrderItemImportDTO, OrdersExportResult as _OrdersExportResult, PaginatedAdjustments as _PaginatedAdjustments, PaginatedArchivedOrders as _PaginatedArchivedOrders, PaginatedOrders as _PaginatedOrders, PaginatedReturns as _PaginatedReturns, Product as _Product, ReceiptData as _ReceiptData, ReturnItem as _ReturnItem, ReturnOrder as _ReturnOrder, ReturnOrderDTO as _ReturnOrderDTO, ReturnResult as _ReturnResult, StoreDetails as _StoreDetails, TaxBreakdown as _TaxBreakdown, TaxBreakdownExportDTO as _TaxBreakdownExportDTO, TaxBreakdownImportDTO as _TaxBreakdownImportDTO, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategory(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async archiveOrders(arg0: bigint, arg1: bigint): Promise<ArchiveResult> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveOrders(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveOrders(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRoleByText(arg0: string, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRoleByText(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRoleByText(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkUpdateCategories(arg0: Array<[bigint, bigint | null, bigint | null]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateCategories(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateCategories(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bulkUpdateProductsByCategory(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpdateProductsByCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpdateProductsByCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async createInventoryAdjustment(arg0: AdjustmentDTO): Promise<AdjustmentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryAdjustment(to_candid_AdjustmentDTO_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdjustmentResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryAdjustment(to_candid_AdjustmentDTO_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdjustmentResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: CreateOrderRequest): Promise<CreateOrderResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateOrderResponse_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateOrderResponse_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReturn(arg0: ReturnOrderDTO): Promise<ReturnResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createReturn(to_candid_ReturnOrderDTO_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ReturnResult_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReturn(to_candid_ReturnOrderDTO_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ReturnResult_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCategory(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0, arg1);
            return result;
        }
    }
    async deleteProduct(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0, arg1);
            return result;
        }
    }
    async exportCategories(): Promise<CategoriesExportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCategories();
            return result;
        }
    }
    async exportOrders(arg0: bigint | null, arg1: bigint | null, arg2: string | null, arg3: string | null): Promise<OrdersExportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.exportOrders(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg3));
                return from_candid_OrdersExportResult_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportOrders(to_candid_opt_n39(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg3));
            return from_candid_OrdersExportResult_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportProducts(arg0: bigint | null, arg1: bigint | null, arg2: bigint | null, arg3: bigint | null, arg4: bigint | null): Promise<ProductsExportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.exportProducts(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportProducts(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async generateReturnReceipt(arg0: bigint): Promise<ReceiptData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReturnReceipt(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReturnReceipt(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArchivePreview(arg0: bigint, arg1: bigint): Promise<ArchivePreviewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivePreview(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivePreview(arg0, arg1);
            return result;
        }
    }
    async getArchivedOrderDetails(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedOrderDetails(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedOrderDetails(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getInventoryAdjustmentAnalytics(arg0: AnalyticsFilters): Promise<AdjustmentAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryAdjustmentAnalytics(to_candid_AnalyticsFilters_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdjustmentAnalytics_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryAdjustmentAnalytics(to_candid_AnalyticsFilters_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdjustmentAnalytics_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedAdjustments(arg0: bigint, arg1: bigint, arg2: AdjustmentFilters): Promise<PaginatedAdjustments> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedAdjustments(arg0, arg1, to_candid_AdjustmentFilters_n62(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PaginatedAdjustments_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedAdjustments(arg0, arg1, to_candid_AdjustmentFilters_n62(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PaginatedAdjustments_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedArchivedOrders(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint | null, arg5: bigint | null): Promise<PaginatedArchivedOrders> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedArchivedOrders(arg0, arg1, arg2, arg3, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
                return from_candid_PaginatedArchivedOrders_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedArchivedOrders(arg0, arg1, arg2, arg3, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
            return from_candid_PaginatedArchivedOrders_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedOrders(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint | null, arg5: bigint | null, arg6: string | null): Promise<PaginatedOrders> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedOrders(arg0, arg1, arg2, arg3, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg6));
                return from_candid_PaginatedOrders_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedOrders(arg0, arg1, arg2, arg3, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg6));
            return from_candid_PaginatedOrders_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaginatedProducts(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: bigint | null, arg6: bigint | null): Promise<PaginatedProducts> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedProducts(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedProducts(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async getPaginatedReturns(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: bigint | null, arg8: bigint | null, arg9: string | null): Promise<PaginatedReturns> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaginatedReturns(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg9));
                return from_candid_PaginatedReturns_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaginatedReturns(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n39(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg9));
            return from_candid_PaginatedReturns_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReturnDetails(arg0: bigint): Promise<ReturnOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReturnDetails(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReturnDetails(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesAnalyticsData(arg0: AnalyticsFilters): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesAnalyticsData(to_candid_AnalyticsFilters_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AnalyticsData_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesAnalyticsData(to_candid_AnalyticsFilters_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AnalyticsData_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreDetails(): Promise<StoreDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreDetails();
                return from_candid_StoreDetails_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreDetails();
            return from_candid_StoreDetails_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async importCategories(arg0: Array<CategoryImportDTO>): Promise<CategoriesImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importCategories(arg0);
            return result;
        }
    }
    async importLegacyCategories(arg0: Array<LegacyCategoryImportDTO>): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importLegacyCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importLegacyCategories(arg0);
            return result;
        }
    }
    async importLegacyProducts(arg0: Array<LegacyProductImportDTO>): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importLegacyProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importLegacyProducts(arg0);
            return result;
        }
    }
    async importOrders(arg0: Array<OrderImportDTO>, arg1: OrderImportConfig): Promise<OrdersImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importOrders(to_candid_vec_n82(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importOrders(to_candid_vec_n82(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async importProducts(arg0: Array<ProductImportDTO>): Promise<ProductsImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.importProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importProducts(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProductsForCheckout(arg0: string, arg1: string, arg2: bigint): Promise<Array<ProductSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProductsForCheckout(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProductsForCheckout(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCategory(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async updateReturnStatus(arg0: bigint, arg1: Variant_pending_rejected_processed, arg2: string | null): Promise<StatusResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReturnStatus(arg0, to_candid_variant_n85(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReturnStatus(arg0, to_candid_variant_n85(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateStoreDetails(arg0: StoreDetails): Promise<{
        message: string;
        success: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreDetails(to_candid_StoreDetails_n86(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreDetails(to_candid_StoreDetails_n86(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AdjustmentAnalytics_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdjustmentAnalytics): AdjustmentAnalytics {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_AdjustmentResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdjustmentResult): AdjustmentResult {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AnalyticsData_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsData): AnalyticsData {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_ArchivedOrder_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArchivedOrder): ArchivedOrder {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_CreateOrderResponse_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateOrderResponse): CreateOrderResponse {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryAdjustment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryAdjustment): InventoryAdjustment {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderExportDTO_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderExportDTO): OrderExportDTO {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrdersExportResult_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrdersExportResult): OrdersExportResult {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedAdjustments_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedAdjustments): PaginatedAdjustments {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedArchivedOrders_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedArchivedOrders): PaginatedArchivedOrders {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedOrders_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedOrders): PaginatedOrders {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedReturns_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedReturns): PaginatedReturns {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_ReceiptData_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReceiptData): ReceiptData {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ReturnOrder_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReturnOrder): ReturnOrder {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ReturnResult_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReturnResult): ReturnResult {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_StoreDetails_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreDetails): StoreDetails {
    return from_candid_record_n81(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_TaxBreakdown>]): Array<TaxBreakdown> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_TaxBreakdownExportDTO>]): Array<TaxBreakdownExportDTO> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReceiptData]): ReceiptData | null {
    return value.length === 0 ? null : from_candid_ReceiptData_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReturnOrder]): ReturnOrder | null {
    return value.length === 0 ? null : from_candid_ReturnOrder_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        name: string;
        amount: bigint;
    }]): {
    name: string;
    amount: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: _InventoryAdjustment;
    warnings: Array<string>;
    success: boolean;
}): {
    adjustment: InventoryAdjustment;
    warnings: Array<string>;
    success: boolean;
} {
    return {
        adjustment: from_candid_InventoryAdjustment_n12(_uploadFile, _downloadFile, value.adjustment),
        warnings: value.warnings,
        success: value.success
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateEffective: bigint;
    productName: string;
    adminUserId: string;
    timestamp: bigint;
    newStock: bigint;
    previousStock: bigint;
    quantity: bigint;
    adjustmentId: bigint;
    adjustmentType: {
        decrease: null;
    } | {
        increase: null;
    };
    adminNotes: string;
    productBarcode: string;
    reason: {
        theft: null;
    } | {
        broken: null;
    } | {
        expired: null;
    } | {
        lost: null;
    } | {
        count: null;
    } | {
        error: null;
    };
}): {
    dateEffective: bigint;
    productName: string;
    adminUserId: string;
    timestamp: bigint;
    newStock: bigint;
    previousStock: bigint;
    quantity: bigint;
    adjustmentId: bigint;
    adjustmentType: Variant_decrease_increase;
    adminNotes: string;
    productBarcode: string;
    reason: Variant_theft_broken_expired_lost_count_error;
} {
    return {
        dateEffective: value.dateEffective,
        productName: value.productName,
        adminUserId: value.adminUserId,
        timestamp: value.timestamp,
        newStock: value.newStock,
        previousStock: value.previousStock,
        quantity: value.quantity,
        adjustmentId: value.adjustmentId,
        adjustmentType: from_candid_variant_n14(_uploadFile, _downloadFile, value.adjustmentType),
        adminNotes: value.adminNotes,
        productBarcode: value.productBarcode,
        reason: from_candid_variant_n15(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: _Order;
    warnings: Array<string>;
    success: boolean;
}): {
    order: Order;
    warnings: Array<string>;
    success: boolean;
} {
    return {
        order: from_candid_Order_n21(_uploadFile, _downloadFile, value.order),
        warnings: value.warnings,
        success: value.success
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: [] | [string];
    status: {
        valid: null;
    } | {
        invalid: null;
    };
    customerNotes: string;
    paymentMethod: {
        card: null;
    } | {
        cash: null;
    } | {
        transfer: null;
    };
    discountAmount: number;
    orderId: string;
    customerTaxId: [] | [string];
    invoiceType: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: bigint;
    taxBreakdown: [] | [Array<_TaxBreakdown>];
    items: Array<_OrderItem>;
    orderNumber: string;
}): {
    customerName?: string;
    status: Variant_valid_invalid;
    customerNotes: string;
    paymentMethod: Variant_card_cash_transfer;
    discountAmount: number;
    orderId: string;
    customerTaxId?: string;
    invoiceType: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: bigint;
    taxBreakdown?: Array<TaxBreakdown>;
    items: Array<OrderItem>;
    orderNumber: string;
} {
    return {
        customerName: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.customerName)),
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        customerNotes: value.customerNotes,
        paymentMethod: from_candid_variant_n25(_uploadFile, _downloadFile, value.paymentMethod),
        discountAmount: value.discountAmount,
        orderId: value.orderId,
        customerTaxId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.customerTaxId)),
        invoiceType: value.invoiceType,
        printReceipt: value.printReceipt,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        taxBreakdown: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.taxBreakdown)),
        items: value.items,
        orderNumber: value.orderNumber
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    returnOrder: _ReturnOrder;
    warnings: Array<string>;
    success: boolean;
}): {
    returnOrder: ReturnOrder;
    warnings: Array<string>;
    success: boolean;
} {
    return {
        returnOrder: from_candid_ReturnOrder_n33(_uploadFile, _downloadFile, value.returnOrder),
        warnings: value.warnings,
        success: value.success
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    refundAmount: number;
    status: {
        pending: null;
    } | {
        rejected: null;
    } | {
        processed: null;
    };
    originalOrderId: string;
    stockRestored: boolean;
    createdDate: bigint;
    items: Array<_ReturnItem>;
    processedDate: [] | [bigint];
    statusChangeNotes: [] | [string];
    returnNumber: string;
    adminNotes: string;
    originalOrderNumber: string;
    returnType: {
        full: null;
    } | {
        cancellation: null;
    } | {
        partial: null;
    };
    returnId: bigint;
    otherReason: [] | [string];
    reason: {
        other: null;
    } | {
        defective: null;
    } | {
        incorrect: null;
    } | {
        change_of_mind: null;
    };
}): {
    refundAmount: number;
    status: Variant_pending_rejected_processed;
    originalOrderId: string;
    stockRestored: boolean;
    createdDate: bigint;
    items: Array<ReturnItem>;
    processedDate?: bigint;
    statusChangeNotes?: string;
    returnNumber: string;
    adminNotes: string;
    originalOrderNumber: string;
    returnType: Variant_full_cancellation_partial;
    returnId: bigint;
    otherReason?: string;
    reason: Variant_other_defective_incorrect_change_of_mind;
} {
    return {
        refundAmount: value.refundAmount,
        status: from_candid_variant_n35(_uploadFile, _downloadFile, value.status),
        originalOrderId: value.originalOrderId,
        stockRestored: value.stockRestored,
        createdDate: value.createdDate,
        items: value.items,
        processedDate: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.processedDate)),
        statusChangeNotes: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.statusChangeNotes)),
        returnNumber: value.returnNumber,
        adminNotes: value.adminNotes,
        originalOrderNumber: value.originalOrderNumber,
        returnType: from_candid_variant_n37(_uploadFile, _downloadFile, value.returnType),
        returnId: value.returnId,
        otherReason: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.otherReason)),
        reason: from_candid_variant_n38(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orders: Array<_OrderExportDTO>;
    totalCount: bigint;
    exportTimestamp: string;
}): {
    orders: Array<OrderExportDTO>;
    totalCount: bigint;
    exportTimestamp: string;
} {
    return {
        orders: from_candid_vec_n43(_uploadFile, _downloadFile, value.orders),
        totalCount: value.totalCount,
        exportTimestamp: value.exportTimestamp
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    customerNotes: string;
    paymentMethod: string;
    discountAmount: number;
    orderId: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: string;
    taxBreakdown: [] | [Array<_TaxBreakdownExportDTO>];
    items: Array<_OrderItemExportDTO>;
    orderNumber: string;
}): {
    status: string;
    customerNotes: string;
    paymentMethod: string;
    discountAmount: number;
    orderId: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: string;
    taxBreakdown?: Array<TaxBreakdownExportDTO>;
    items: Array<OrderItemExportDTO>;
    orderNumber: string;
} {
    return {
        status: value.status,
        customerNotes: value.customerNotes,
        paymentMethod: value.paymentMethod,
        discountAmount: value.discountAmount,
        orderId: value.orderId,
        printReceipt: value.printReceipt,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        taxBreakdown: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.taxBreakdown)),
        items: value.items,
        orderNumber: value.orderNumber
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: [] | [_Order];
    receiptType: {
        order: null;
    } | {
        returnOrder: null;
    };
    returnOrder: [] | [_ReturnOrder];
    storeInfo: {
        name: string;
        whatsapp: string;
        address: string;
        phone: string;
    };
    timestamp: bigint;
}): {
    order?: Order;
    receiptType: Variant_order_returnOrder;
    returnOrder?: ReturnOrder;
    storeInfo: {
        name: string;
        whatsapp: string;
        address: string;
        phone: string;
    };
    timestamp: bigint;
} {
    return {
        order: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.order)),
        receiptType: from_candid_variant_n51(_uploadFile, _downloadFile, value.receiptType),
        returnOrder: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.returnOrder)),
        storeInfo: value.storeInfo,
        timestamp: value.timestamp
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValueLost: number;
    mostAffectedProduct: [] | [{
            name: string;
            amount: bigint;
        }];
    totalAdjustments: bigint;
    primaryReason: [] | [string];
}): {
    totalValueLost: number;
    mostAffectedProduct?: {
        name: string;
        amount: bigint;
    };
    totalAdjustments: bigint;
    primaryReason?: string;
} {
    return {
        totalValueLost: value.totalValueLost,
        mostAffectedProduct: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.mostAffectedProduct)),
        totalAdjustments: value.totalAdjustments,
        primaryReason: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.primaryReason))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    adjustments: Array<_InventoryAdjustment>;
}): {
    totalCount: bigint;
    adjustments: Array<InventoryAdjustment>;
} {
    return {
        totalCount: value.totalCount,
        adjustments: from_candid_vec_n66(_uploadFile, _downloadFile, value.adjustments)
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orders: Array<_ArchivedOrder>;
    totalCount: bigint;
}): {
    orders: Array<ArchivedOrder>;
    totalCount: bigint;
} {
    return {
        orders: from_candid_vec_n69(_uploadFile, _downloadFile, value.orders),
        totalCount: value.totalCount
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: _Order;
    archiveDate: bigint;
}): {
    order: Order;
    archiveDate: bigint;
} {
    return {
        order: from_candid_Order_n21(_uploadFile, _downloadFile, value.order),
        archiveDate: value.archiveDate
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orders: Array<_Order>;
    totalCount: bigint;
}): {
    orders: Array<Order>;
    totalCount: bigint;
} {
    return {
        orders: from_candid_vec_n61(_uploadFile, _downloadFile, value.orders),
        totalCount: value.totalCount
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    returns: Array<_ReturnOrder>;
}): {
    totalCount: bigint;
    returns: Array<ReturnOrder>;
} {
    return {
        totalCount: value.totalCount,
        returns: from_candid_vec_n76(_uploadFile, _downloadFile, value.returns)
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    archivedOrders: Array<_Order>;
    activeOrders: Array<_Order>;
}): {
    archivedOrders: Array<Order>;
    activeOrders: Array<Order>;
} {
    return {
        archivedOrders: from_candid_vec_n61(_uploadFile, _downloadFile, value.archivedOrders),
        activeOrders: from_candid_vec_n61(_uploadFile, _downloadFile, value.activeOrders)
    };
}
function from_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxId: [] | [string];
    lastUpdated: bigint;
    whatsapp: string;
    email: [] | [string];
    website: [] | [string];
    address: string;
    storeName: string;
    phone: string;
}): {
    taxId?: string;
    lastUpdated: bigint;
    whatsapp: string;
    email?: string;
    website?: string;
    address: string;
    storeName: string;
    phone: string;
} {
    return {
        taxId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.taxId)),
        lastUpdated: value.lastUpdated,
        whatsapp: value.whatsapp,
        email: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.email)),
        website: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.website)),
        address: value.address,
        storeName: value.storeName,
        phone: value.phone
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    decrease: null;
} | {
    increase: null;
}): Variant_decrease_increase {
    return "decrease" in value ? Variant_decrease_increase.decrease : "increase" in value ? Variant_decrease_increase.increase : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theft: null;
} | {
    broken: null;
} | {
    expired: null;
} | {
    lost: null;
} | {
    count: null;
} | {
    error: null;
}): Variant_theft_broken_expired_lost_count_error {
    return "theft" in value ? Variant_theft_broken_expired_lost_count_error.theft : "broken" in value ? Variant_theft_broken_expired_lost_count_error.broken : "expired" in value ? Variant_theft_broken_expired_lost_count_error.expired : "lost" in value ? Variant_theft_broken_expired_lost_count_error.lost : "count" in value ? Variant_theft_broken_expired_lost_count_error.count : "error" in value ? Variant_theft_broken_expired_lost_count_error.error : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    valid: null;
} | {
    invalid: null;
}): Variant_valid_invalid {
    return "valid" in value ? Variant_valid_invalid.valid : "invalid" in value ? Variant_valid_invalid.invalid : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    card: null;
} | {
    cash: null;
} | {
    transfer: null;
}): Variant_card_cash_transfer {
    return "card" in value ? Variant_card_cash_transfer.card : "cash" in value ? Variant_card_cash_transfer.cash : "transfer" in value ? Variant_card_cash_transfer.transfer : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    processed: null;
}): Variant_pending_rejected_processed {
    return "pending" in value ? Variant_pending_rejected_processed.pending : "rejected" in value ? Variant_pending_rejected_processed.rejected : "processed" in value ? Variant_pending_rejected_processed.processed : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    full: null;
} | {
    cancellation: null;
} | {
    partial: null;
}): Variant_full_cancellation_partial {
    return "full" in value ? Variant_full_cancellation_partial.full : "cancellation" in value ? Variant_full_cancellation_partial.cancellation : "partial" in value ? Variant_full_cancellation_partial.partial : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    defective: null;
} | {
    incorrect: null;
} | {
    change_of_mind: null;
}): Variant_other_defective_incorrect_change_of_mind {
    return "other" in value ? Variant_other_defective_incorrect_change_of_mind.other : "defective" in value ? Variant_other_defective_incorrect_change_of_mind.defective : "incorrect" in value ? Variant_other_defective_incorrect_change_of_mind.incorrect : "change_of_mind" in value ? Variant_other_defective_incorrect_change_of_mind.change_of_mind : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: null;
} | {
    returnOrder: null;
}): Variant_order_returnOrder {
    return "order" in value ? Variant_order_returnOrder.order : "returnOrder" in value ? Variant_order_returnOrder.returnOrder : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderExportDTO>): Array<OrderExportDTO> {
    return value.map((x)=>from_candid_OrderExportDTO_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryAdjustment>): Array<InventoryAdjustment> {
    return value.map((x)=>from_candid_InventoryAdjustment_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArchivedOrder>): Array<ArchivedOrder> {
    return value.map((x)=>from_candid_ArchivedOrder_n70(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReturnOrder>): Array<ReturnOrder> {
    return value.map((x)=>from_candid_ReturnOrder_n33(_uploadFile, _downloadFile, x));
}
function to_candid_AdjustmentDTO_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdjustmentDTO): _AdjustmentDTO {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_AdjustmentFilters_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdjustmentFilters): _AdjustmentFilters {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_AnalyticsFilters_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsFilters): _AnalyticsFilters {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderRequest): _CreateOrderRequest {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_OrderImportDTO_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderImportDTO): _OrderImportDTO {
    return to_candid_record_n84(_uploadFile, _downloadFile, value);
}
function to_candid_ReturnOrderDTO_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReturnOrderDTO): _ReturnOrderDTO {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_StoreDetails_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreDetails): _StoreDetails {
    return to_candid_record_n87(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName?: string;
    customerNotes: string;
    paymentMethod: Variant_card_cash_transfer;
    discountAmount: number;
    customerTaxId?: string;
    invoiceType: string;
    printReceipt: boolean;
    taxBreakdown?: Array<TaxBreakdown>;
    items: Array<OrderItem>;
}): {
    customerName: [] | [string];
    customerNotes: string;
    paymentMethod: {
        card: null;
    } | {
        cash: null;
    } | {
        transfer: null;
    };
    discountAmount: number;
    customerTaxId: [] | [string];
    invoiceType: string;
    printReceipt: boolean;
    taxBreakdown: [] | [Array<_TaxBreakdown>];
    items: Array<_OrderItem>;
} {
    return {
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        customerNotes: value.customerNotes,
        paymentMethod: to_candid_variant_n18(_uploadFile, _downloadFile, value.paymentMethod),
        discountAmount: value.discountAmount,
        customerTaxId: value.customerTaxId ? candid_some(value.customerTaxId) : candid_none(),
        invoiceType: value.invoiceType,
        printReceipt: value.printReceipt,
        taxBreakdown: value.taxBreakdown ? candid_some(value.taxBreakdown) : candid_none(),
        items: value.items
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    refundAmount: number;
    originalOrderId: string;
    items: Array<ReturnItem>;
    adminNotes: string;
    originalOrderNumber: string;
    returnType: Variant_full_cancellation_partial;
    otherReason?: string;
    reason: Variant_other_defective_incorrect_change_of_mind;
}): {
    refundAmount: number;
    originalOrderId: string;
    items: Array<_ReturnItem>;
    adminNotes: string;
    originalOrderNumber: string;
    returnType: {
        full: null;
    } | {
        cancellation: null;
    } | {
        partial: null;
    };
    otherReason: [] | [string];
    reason: {
        other: null;
    } | {
        defective: null;
    } | {
        incorrect: null;
    } | {
        change_of_mind: null;
    };
} {
    return {
        refundAmount: value.refundAmount,
        originalOrderId: value.originalOrderId,
        items: value.items,
        adminNotes: value.adminNotes,
        originalOrderNumber: value.originalOrderNumber,
        returnType: to_candid_variant_n29(_uploadFile, _downloadFile, value.returnType),
        otherReason: value.otherReason ? candid_some(value.otherReason) : candid_none(),
        reason: to_candid_variant_n30(_uploadFile, _downloadFile, value.reason)
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryFilter?: bigint;
    paymentMethodFilter?: string;
    toDate: bigint;
    includeArchived: boolean;
    fromDate: bigint;
}): {
    categoryFilter: [] | [bigint];
    paymentMethodFilter: [] | [string];
    toDate: bigint;
    includeArchived: boolean;
    fromDate: bigint;
} {
    return {
        categoryFilter: value.categoryFilter ? candid_some(value.categoryFilter) : candid_none(),
        paymentMethodFilter: value.paymentMethodFilter ? candid_some(value.paymentMethodFilter) : candid_none(),
        toDate: value.toDate,
        includeArchived: value.includeArchived,
        fromDate: value.fromDate
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reasonFilter?: string;
    adjustmentTypeFilter?: string;
    toDate?: bigint;
    fromDate?: bigint;
    productSearch?: string;
}): {
    reasonFilter: [] | [string];
    adjustmentTypeFilter: [] | [string];
    toDate: [] | [bigint];
    fromDate: [] | [bigint];
    productSearch: [] | [string];
} {
    return {
        reasonFilter: value.reasonFilter ? candid_some(value.reasonFilter) : candid_none(),
        adjustmentTypeFilter: value.adjustmentTypeFilter ? candid_some(value.adjustmentTypeFilter) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        productSearch: value.productSearch ? candid_some(value.productSearch) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateEffective: bigint;
    quantity: bigint;
    adjustmentType: Variant_decrease_increase;
    adminNotes: string;
    productBarcode: string;
    reason: Variant_theft_broken_expired_lost_count_error;
}): {
    dateEffective: bigint;
    quantity: bigint;
    adjustmentType: {
        decrease: null;
    } | {
        increase: null;
    };
    adminNotes: string;
    productBarcode: string;
    reason: {
        theft: null;
    } | {
        broken: null;
    } | {
        expired: null;
    } | {
        lost: null;
    } | {
        count: null;
    } | {
        error: null;
    };
} {
    return {
        dateEffective: value.dateEffective,
        quantity: value.quantity,
        adjustmentType: to_candid_variant_n8(_uploadFile, _downloadFile, value.adjustmentType),
        adminNotes: value.adminNotes,
        productBarcode: value.productBarcode,
        reason: to_candid_variant_n9(_uploadFile, _downloadFile, value.reason)
    };
}
function to_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    customerNotes: string;
    paymentMethod: string;
    discountAmount: number;
    orderId: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: bigint;
    taxBreakdown?: Array<TaxBreakdownImportDTO>;
    items: Array<OrderItemImportDTO>;
    orderNumber: string;
}): {
    status: string;
    customerNotes: string;
    paymentMethod: string;
    discountAmount: number;
    orderId: string;
    printReceipt: boolean;
    totalAmount: number;
    timestamp: bigint;
    taxBreakdown: [] | [Array<_TaxBreakdownImportDTO>];
    items: Array<_OrderItemImportDTO>;
    orderNumber: string;
} {
    return {
        status: value.status,
        customerNotes: value.customerNotes,
        paymentMethod: value.paymentMethod,
        discountAmount: value.discountAmount,
        orderId: value.orderId,
        printReceipt: value.printReceipt,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        taxBreakdown: value.taxBreakdown ? candid_some(value.taxBreakdown) : candid_none(),
        items: value.items,
        orderNumber: value.orderNumber
    };
}
function to_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxId?: string;
    lastUpdated: bigint;
    whatsapp: string;
    email?: string;
    website?: string;
    address: string;
    storeName: string;
    phone: string;
}): {
    taxId: [] | [string];
    lastUpdated: bigint;
    whatsapp: string;
    email: [] | [string];
    website: [] | [string];
    address: string;
    storeName: string;
    phone: string;
} {
    return {
        taxId: value.taxId ? candid_some(value.taxId) : candid_none(),
        lastUpdated: value.lastUpdated,
        whatsapp: value.whatsapp,
        email: value.email ? candid_some(value.email) : candid_none(),
        website: value.website ? candid_some(value.website) : candid_none(),
        address: value.address,
        storeName: value.storeName,
        phone: value.phone
    };
}
function to_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, bigint | null, bigint | null]): [bigint, [] | [bigint], [] | [bigint]] {
    return [
        value[0],
        to_candid_opt_n5(_uploadFile, _downloadFile, value[1]),
        to_candid_opt_n5(_uploadFile, _downloadFile, value[2])
    ];
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_card_cash_transfer): {
    card: null;
} | {
    cash: null;
} | {
    transfer: null;
} {
    return value == Variant_card_cash_transfer.card ? {
        card: null
    } : value == Variant_card_cash_transfer.cash ? {
        cash: null
    } : value == Variant_card_cash_transfer.transfer ? {
        transfer: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_full_cancellation_partial): {
    full: null;
} | {
    cancellation: null;
} | {
    partial: null;
} {
    return value == Variant_full_cancellation_partial.full ? {
        full: null
    } : value == Variant_full_cancellation_partial.cancellation ? {
        cancellation: null
    } : value == Variant_full_cancellation_partial.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_other_defective_incorrect_change_of_mind): {
    other: null;
} | {
    defective: null;
} | {
    incorrect: null;
} | {
    change_of_mind: null;
} {
    return value == Variant_other_defective_incorrect_change_of_mind.other ? {
        other: null
    } : value == Variant_other_defective_incorrect_change_of_mind.defective ? {
        defective: null
    } : value == Variant_other_defective_incorrect_change_of_mind.incorrect ? {
        incorrect: null
    } : value == Variant_other_defective_incorrect_change_of_mind.change_of_mind ? {
        change_of_mind: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_decrease_increase): {
    decrease: null;
} | {
    increase: null;
} {
    return value == Variant_decrease_increase.decrease ? {
        decrease: null
    } : value == Variant_decrease_increase.increase ? {
        increase: null
    } : value;
}
function to_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_rejected_processed): {
    pending: null;
} | {
    rejected: null;
} | {
    processed: null;
} {
    return value == Variant_pending_rejected_processed.pending ? {
        pending: null
    } : value == Variant_pending_rejected_processed.rejected ? {
        rejected: null
    } : value == Variant_pending_rejected_processed.processed ? {
        processed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_theft_broken_expired_lost_count_error): {
    theft: null;
} | {
    broken: null;
} | {
    expired: null;
} | {
    lost: null;
} | {
    count: null;
} | {
    error: null;
} {
    return value == Variant_theft_broken_expired_lost_count_error.theft ? {
        theft: null
    } : value == Variant_theft_broken_expired_lost_count_error.broken ? {
        broken: null
    } : value == Variant_theft_broken_expired_lost_count_error.expired ? {
        expired: null
    } : value == Variant_theft_broken_expired_lost_count_error.lost ? {
        lost: null
    } : value == Variant_theft_broken_expired_lost_count_error.count ? {
        count: null
    } : value == Variant_theft_broken_expired_lost_count_error.error ? {
        error: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, bigint | null, bigint | null]>): Array<[bigint, [] | [bigint], [] | [bigint]]> {
    return value.map((x)=>to_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderImportDTO>): Array<_OrderImportDTO> {
    return value.map((x)=>to_candid_OrderImportDTO_n83(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
