/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'iva' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'updatedDate' : IDL.Int,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
});
export const ArchiveResult = IDL.Record({
  'archivedCount' : IDL.Nat,
  'archivedIds' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdjustmentDTO = IDL.Record({
  'dateEffective' : IDL.Int,
  'quantity' : IDL.Nat,
  'adjustmentType' : IDL.Variant({
    'decrease' : IDL.Null,
    'increase' : IDL.Null,
  }),
  'adminNotes' : IDL.Text,
  'productBarcode' : IDL.Text,
  'reason' : IDL.Variant({
    'theft' : IDL.Null,
    'broken' : IDL.Null,
    'expired' : IDL.Null,
    'lost' : IDL.Null,
    'count' : IDL.Null,
    'error' : IDL.Null,
  }),
});
export const InventoryAdjustment = IDL.Record({
  'dateEffective' : IDL.Int,
  'productName' : IDL.Text,
  'adminUserId' : IDL.Text,
  'timestamp' : IDL.Int,
  'newStock' : IDL.Nat,
  'previousStock' : IDL.Nat,
  'quantity' : IDL.Nat,
  'adjustmentId' : IDL.Nat,
  'adjustmentType' : IDL.Variant({
    'decrease' : IDL.Null,
    'increase' : IDL.Null,
  }),
  'adminNotes' : IDL.Text,
  'productBarcode' : IDL.Text,
  'reason' : IDL.Variant({
    'theft' : IDL.Null,
    'broken' : IDL.Null,
    'expired' : IDL.Null,
    'lost' : IDL.Null,
    'count' : IDL.Null,
    'error' : IDL.Null,
  }),
});
export const AdjustmentResult = IDL.Record({
  'adjustment' : InventoryAdjustment,
  'warnings' : IDL.Vec(IDL.Text),
  'success' : IDL.Bool,
});
export const TaxBreakdown = IDL.Record({
  'taxableAmount' : IDL.Float64,
  'ivaRate' : IDL.Nat,
  'baseAmount' : IDL.Float64,
  'taxAmount' : IDL.Float64,
});
export const OrderItem = IDL.Record({
  'categoryName' : IDL.Text,
  'ivaRate' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'salePrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
  'productBarcode' : IDL.Text,
  'updatedStock' : IDL.Nat,
  'originalStock' : IDL.Nat,
});
export const CreateOrderRequest = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'customerNotes' : IDL.Text,
  'paymentMethod' : IDL.Variant({
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'transfer' : IDL.Null,
  }),
  'discountAmount' : IDL.Float64,
  'customerTaxId' : IDL.Opt(IDL.Text),
  'invoiceType' : IDL.Text,
  'printReceipt' : IDL.Bool,
  'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdown)),
  'items' : IDL.Vec(OrderItem),
});
export const Order = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'status' : IDL.Variant({ 'valid' : IDL.Null, 'invalid' : IDL.Null }),
  'customerNotes' : IDL.Text,
  'paymentMethod' : IDL.Variant({
    'card' : IDL.Null,
    'cash' : IDL.Null,
    'transfer' : IDL.Null,
  }),
  'discountAmount' : IDL.Float64,
  'orderId' : IDL.Text,
  'customerTaxId' : IDL.Opt(IDL.Text),
  'invoiceType' : IDL.Text,
  'printReceipt' : IDL.Bool,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdown)),
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : IDL.Text,
});
export const CreateOrderResponse = IDL.Record({
  'order' : Order,
  'warnings' : IDL.Vec(IDL.Text),
  'success' : IDL.Bool,
});
export const ReturnItem = IDL.Record({
  'returnedQuantity' : IDL.Nat,
  'categoryName' : IDL.Text,
  'stockRestored' : IDL.Bool,
  'originalQuantity' : IDL.Nat,
  'productName' : IDL.Text,
  'refundPerUnit' : IDL.Float64,
  'totalRefund' : IDL.Float64,
  'productBarcode' : IDL.Text,
});
export const ReturnOrderDTO = IDL.Record({
  'refundAmount' : IDL.Float64,
  'originalOrderId' : IDL.Text,
  'items' : IDL.Vec(ReturnItem),
  'adminNotes' : IDL.Text,
  'originalOrderNumber' : IDL.Text,
  'returnType' : IDL.Variant({
    'full' : IDL.Null,
    'cancellation' : IDL.Null,
    'partial' : IDL.Null,
  }),
  'otherReason' : IDL.Opt(IDL.Text),
  'reason' : IDL.Variant({
    'other' : IDL.Null,
    'defective' : IDL.Null,
    'incorrect' : IDL.Null,
    'change_of_mind' : IDL.Null,
  }),
});
export const ReturnOrder = IDL.Record({
  'refundAmount' : IDL.Float64,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'processed' : IDL.Null,
  }),
  'originalOrderId' : IDL.Text,
  'stockRestored' : IDL.Bool,
  'createdDate' : IDL.Int,
  'items' : IDL.Vec(ReturnItem),
  'processedDate' : IDL.Opt(IDL.Int),
  'statusChangeNotes' : IDL.Opt(IDL.Text),
  'returnNumber' : IDL.Text,
  'adminNotes' : IDL.Text,
  'originalOrderNumber' : IDL.Text,
  'returnType' : IDL.Variant({
    'full' : IDL.Null,
    'cancellation' : IDL.Null,
    'partial' : IDL.Null,
  }),
  'returnId' : IDL.Nat,
  'otherReason' : IDL.Opt(IDL.Text),
  'reason' : IDL.Variant({
    'other' : IDL.Null,
    'defective' : IDL.Null,
    'incorrect' : IDL.Null,
    'change_of_mind' : IDL.Null,
  }),
});
export const ReturnResult = IDL.Record({
  'returnOrder' : ReturnOrder,
  'warnings' : IDL.Vec(IDL.Text),
  'success' : IDL.Bool,
});
export const CategoryExportDTO = IDL.Record({
  'id' : IDL.Nat,
  'defaultIVA' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'defaultProfitMargin' : IDL.Nat,
  'productCount' : IDL.Nat,
});
export const CategoriesExportResult = IDL.Record({
  'categories' : IDL.Vec(CategoryExportDTO),
  'totalCount' : IDL.Nat,
  'exportTimestamp' : IDL.Text,
});
export const TaxBreakdownExportDTO = IDL.Record({
  'taxableAmount' : IDL.Float64,
  'ivaRate' : IDL.Nat,
  'baseAmount' : IDL.Float64,
  'taxAmount' : IDL.Float64,
});
export const OrderItemExportDTO = IDL.Record({
  'categoryName' : IDL.Text,
  'ivaRate' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'salePrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
  'productBarcode' : IDL.Text,
});
export const OrderExportDTO = IDL.Record({
  'status' : IDL.Text,
  'customerNotes' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'discountAmount' : IDL.Float64,
  'orderId' : IDL.Text,
  'printReceipt' : IDL.Bool,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Text,
  'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdownExportDTO)),
  'items' : IDL.Vec(OrderItemExportDTO),
  'orderNumber' : IDL.Text,
});
export const OrdersExportResult = IDL.Record({
  'orders' : IDL.Vec(OrderExportDTO),
  'totalCount' : IDL.Nat,
  'exportTimestamp' : IDL.Text,
});
export const ProductExportDTO = IDL.Record({
  'iva' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'updatedDate' : IDL.Text,
  'name' : IDL.Text,
  'createdDate' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'salePrice' : IDL.Float64,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
});
export const ProductsExportResult = IDL.Record({
  'totalCount' : IDL.Nat,
  'products' : IDL.Vec(ProductExportDTO),
  'exportTimestamp' : IDL.Text,
});
export const ReceiptData = IDL.Record({
  'order' : IDL.Opt(Order),
  'receiptType' : IDL.Variant({ 'order' : IDL.Null, 'returnOrder' : IDL.Null }),
  'returnOrder' : IDL.Opt(ReturnOrder),
  'storeInfo' : IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  }),
  'timestamp' : IDL.Int,
});
export const ArchivePreviewResult = IDL.Record({ 'orderCount' : IDL.Nat });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'defaultIVA' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'defaultProfitMargin' : IDL.Nat,
});
export const AnalyticsFilters = IDL.Record({
  'categoryFilter' : IDL.Opt(IDL.Nat),
  'paymentMethodFilter' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Int,
  'includeArchived' : IDL.Bool,
  'fromDate' : IDL.Int,
});
export const AdjustmentAnalytics = IDL.Record({
  'totalValueLost' : IDL.Float64,
  'mostAffectedProduct' : IDL.Opt(
    IDL.Record({ 'name' : IDL.Text, 'amount' : IDL.Nat })
  ),
  'totalAdjustments' : IDL.Nat,
  'primaryReason' : IDL.Opt(IDL.Text),
});
export const AdjustmentFilters = IDL.Record({
  'reasonFilter' : IDL.Opt(IDL.Text),
  'adjustmentTypeFilter' : IDL.Opt(IDL.Text),
  'toDate' : IDL.Opt(IDL.Int),
  'fromDate' : IDL.Opt(IDL.Int),
  'productSearch' : IDL.Opt(IDL.Text),
});
export const PaginatedAdjustments = IDL.Record({
  'totalCount' : IDL.Nat,
  'adjustments' : IDL.Vec(InventoryAdjustment),
});
export const ArchivedOrder = IDL.Record({
  'order' : Order,
  'archiveDate' : IDL.Int,
});
export const PaginatedArchivedOrders = IDL.Record({
  'orders' : IDL.Vec(ArchivedOrder),
  'totalCount' : IDL.Nat,
});
export const PaginatedOrders = IDL.Record({
  'orders' : IDL.Vec(Order),
  'totalCount' : IDL.Nat,
});
export const ProductWithCategory = IDL.Record({
  'categoryName' : IDL.Text,
  'product' : Product,
});
export const PaginatedProducts = IDL.Record({
  'totalCount' : IDL.Nat,
  'products' : IDL.Vec(ProductWithCategory),
});
export const PaginatedReturns = IDL.Record({
  'totalCount' : IDL.Nat,
  'returns' : IDL.Vec(ReturnOrder),
});
export const AnalyticsData = IDL.Record({
  'archivedOrders' : IDL.Vec(Order),
  'activeOrders' : IDL.Vec(Order),
});
export const StoreDetails = IDL.Record({
  'taxId' : IDL.Opt(IDL.Text),
  'lastUpdated' : IDL.Int,
  'whatsapp' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'storeName' : IDL.Text,
  'phone' : IDL.Text,
});
export const CategoryImportDTO = IDL.Record({
  'categoryId' : IDL.Nat,
  'defaultIVA' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'defaultProfitMargin' : IDL.Nat,
});
export const CategoriesImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'importedCount' : IDL.Nat,
  'errorCount' : IDL.Nat,
  'skippedCount' : IDL.Nat,
});
export const LegacyCategoryImportDTO = IDL.Record({
  'defaultIVA' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'defaultProfitMargin' : IDL.Nat,
});
export const ImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'successCount' : IDL.Nat,
  'errorCount' : IDL.Nat,
});
export const LegacyProductImportDTO = IDL.Record({
  'categoryName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'salePrice' : IDL.Float64,
});
export const TaxBreakdownImportDTO = IDL.Record({
  'taxableAmount' : IDL.Float64,
  'ivaRate' : IDL.Nat,
  'baseAmount' : IDL.Float64,
  'taxAmount' : IDL.Float64,
});
export const OrderItemImportDTO = IDL.Record({
  'categoryName' : IDL.Text,
  'ivaRate' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'salePrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
  'productBarcode' : IDL.Text,
  'updatedStock' : IDL.Nat,
  'originalStock' : IDL.Nat,
});
export const OrderImportDTO = IDL.Record({
  'status' : IDL.Text,
  'customerNotes' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'discountAmount' : IDL.Float64,
  'orderId' : IDL.Text,
  'printReceipt' : IDL.Bool,
  'totalAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
  'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdownImportDTO)),
  'items' : IDL.Vec(OrderItemImportDTO),
  'orderNumber' : IDL.Text,
});
export const OrderImportConfig = IDL.Record({
  'targetDataset' : IDL.Text,
  'preserveTimestamps' : IDL.Bool,
  'updateStock' : IDL.Bool,
  'conflictResolution' : IDL.Text,
});
export const OrdersImportResult = IDL.Record({
  'resultDetails' : IDL.Vec(IDL.Text),
  'nextOrderId' : IDL.Nat,
  'errors' : IDL.Vec(IDL.Text),
  'importedCount' : IDL.Nat,
  'updatedCount' : IDL.Nat,
  'errorCount' : IDL.Nat,
  'skippedCount' : IDL.Nat,
});
export const ProductImportDTO = IDL.Record({
  'iva' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'updatedDate' : IDL.Int,
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
});
export const ProductsImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Text),
  'importedCount' : IDL.Nat,
  'errorCount' : IDL.Nat,
  'skippedCount' : IDL.Nat,
});
export const ProductSearchResult = IDL.Record({
  'iva' : IDL.Nat,
  'categoryName' : IDL.Text,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
  'profitMargin' : IDL.Nat,
  'basePrice' : IDL.Float64,
});
export const StatusResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addCategory' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func([Product], [], []),
  'archiveOrders' : IDL.Func([IDL.Int, IDL.Int], [ArchiveResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCallerUserRoleByText' : IDL.Func([IDL.Text, UserRole], [], []),
  'bulkUpdateCategories' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)))],
      [],
      [],
    ),
  'bulkUpdateProductsByCategory' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'createInventoryAdjustment' : IDL.Func(
      [AdjustmentDTO],
      [AdjustmentResult],
      [],
    ),
  'createOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResponse], []),
  'createReturn' : IDL.Func([ReturnOrderDTO], [ReturnResult], []),
  'deleteCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'exportCategories' : IDL.Func([], [CategoriesExportResult], ['query']),
  'exportOrders' : IDL.Func(
      [
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [OrdersExportResult],
      ['query'],
    ),
  'exportProducts' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
      ],
      [ProductsExportResult],
      ['query'],
    ),
  'generateReturnReceipt' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ReceiptData)],
      ['query'],
    ),
  'getArchivePreview' : IDL.Func(
      [IDL.Int, IDL.Int],
      [ArchivePreviewResult],
      ['query'],
    ),
  'getArchivedOrderDetails' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getInventoryAdjustmentAnalytics' : IDL.Func(
      [AnalyticsFilters],
      [AdjustmentAnalytics],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPaginatedAdjustments' : IDL.Func(
      [IDL.Nat, IDL.Nat, AdjustmentFilters],
      [PaginatedAdjustments],
      ['query'],
    ),
  'getPaginatedArchivedOrders' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
      ],
      [PaginatedArchivedOrders],
      ['query'],
    ),
  'getPaginatedOrders' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
      ],
      [PaginatedOrders],
      ['query'],
    ),
  'getPaginatedProducts' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [PaginatedProducts],
      ['query'],
    ),
  'getPaginatedReturns' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
      ],
      [PaginatedReturns],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getReturnDetails' : IDL.Func([IDL.Nat], [IDL.Opt(ReturnOrder)], ['query']),
  'getSalesAnalyticsData' : IDL.Func(
      [AnalyticsFilters],
      [AnalyticsData],
      ['query'],
    ),
  'getStoreDetails' : IDL.Func([], [StoreDetails], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importCategories' : IDL.Func(
      [IDL.Vec(CategoryImportDTO)],
      [CategoriesImportResult],
      [],
    ),
  'importLegacyCategories' : IDL.Func(
      [IDL.Vec(LegacyCategoryImportDTO)],
      [ImportResult],
      [],
    ),
  'importLegacyProducts' : IDL.Func(
      [IDL.Vec(LegacyProductImportDTO)],
      [ImportResult],
      [],
    ),
  'importOrders' : IDL.Func(
      [IDL.Vec(OrderImportDTO), OrderImportConfig],
      [OrdersImportResult],
      [],
    ),
  'importProducts' : IDL.Func(
      [IDL.Vec(ProductImportDTO)],
      [ProductsImportResult],
      [],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProductsForCheckout' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(ProductSearchResult)],
      ['query'],
    ),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateReturnStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'rejected' : IDL.Null,
          'processed' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [StatusResult],
      [],
    ),
  'updateStoreDetails' : IDL.Func(
      [StoreDetails],
      [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'iva' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'updatedDate' : IDL.Int,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
  });
  const ArchiveResult = IDL.Record({
    'archivedCount' : IDL.Nat,
    'archivedIds' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdjustmentDTO = IDL.Record({
    'dateEffective' : IDL.Int,
    'quantity' : IDL.Nat,
    'adjustmentType' : IDL.Variant({
      'decrease' : IDL.Null,
      'increase' : IDL.Null,
    }),
    'adminNotes' : IDL.Text,
    'productBarcode' : IDL.Text,
    'reason' : IDL.Variant({
      'theft' : IDL.Null,
      'broken' : IDL.Null,
      'expired' : IDL.Null,
      'lost' : IDL.Null,
      'count' : IDL.Null,
      'error' : IDL.Null,
    }),
  });
  const InventoryAdjustment = IDL.Record({
    'dateEffective' : IDL.Int,
    'productName' : IDL.Text,
    'adminUserId' : IDL.Text,
    'timestamp' : IDL.Int,
    'newStock' : IDL.Nat,
    'previousStock' : IDL.Nat,
    'quantity' : IDL.Nat,
    'adjustmentId' : IDL.Nat,
    'adjustmentType' : IDL.Variant({
      'decrease' : IDL.Null,
      'increase' : IDL.Null,
    }),
    'adminNotes' : IDL.Text,
    'productBarcode' : IDL.Text,
    'reason' : IDL.Variant({
      'theft' : IDL.Null,
      'broken' : IDL.Null,
      'expired' : IDL.Null,
      'lost' : IDL.Null,
      'count' : IDL.Null,
      'error' : IDL.Null,
    }),
  });
  const AdjustmentResult = IDL.Record({
    'adjustment' : InventoryAdjustment,
    'warnings' : IDL.Vec(IDL.Text),
    'success' : IDL.Bool,
  });
  const TaxBreakdown = IDL.Record({
    'taxableAmount' : IDL.Float64,
    'ivaRate' : IDL.Nat,
    'baseAmount' : IDL.Float64,
    'taxAmount' : IDL.Float64,
  });
  const OrderItem = IDL.Record({
    'categoryName' : IDL.Text,
    'ivaRate' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'salePrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
    'productBarcode' : IDL.Text,
    'updatedStock' : IDL.Nat,
    'originalStock' : IDL.Nat,
  });
  const CreateOrderRequest = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'customerNotes' : IDL.Text,
    'paymentMethod' : IDL.Variant({
      'card' : IDL.Null,
      'cash' : IDL.Null,
      'transfer' : IDL.Null,
    }),
    'discountAmount' : IDL.Float64,
    'customerTaxId' : IDL.Opt(IDL.Text),
    'invoiceType' : IDL.Text,
    'printReceipt' : IDL.Bool,
    'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdown)),
    'items' : IDL.Vec(OrderItem),
  });
  const Order = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'status' : IDL.Variant({ 'valid' : IDL.Null, 'invalid' : IDL.Null }),
    'customerNotes' : IDL.Text,
    'paymentMethod' : IDL.Variant({
      'card' : IDL.Null,
      'cash' : IDL.Null,
      'transfer' : IDL.Null,
    }),
    'discountAmount' : IDL.Float64,
    'orderId' : IDL.Text,
    'customerTaxId' : IDL.Opt(IDL.Text),
    'invoiceType' : IDL.Text,
    'printReceipt' : IDL.Bool,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdown)),
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : IDL.Text,
  });
  const CreateOrderResponse = IDL.Record({
    'order' : Order,
    'warnings' : IDL.Vec(IDL.Text),
    'success' : IDL.Bool,
  });
  const ReturnItem = IDL.Record({
    'returnedQuantity' : IDL.Nat,
    'categoryName' : IDL.Text,
    'stockRestored' : IDL.Bool,
    'originalQuantity' : IDL.Nat,
    'productName' : IDL.Text,
    'refundPerUnit' : IDL.Float64,
    'totalRefund' : IDL.Float64,
    'productBarcode' : IDL.Text,
  });
  const ReturnOrderDTO = IDL.Record({
    'refundAmount' : IDL.Float64,
    'originalOrderId' : IDL.Text,
    'items' : IDL.Vec(ReturnItem),
    'adminNotes' : IDL.Text,
    'originalOrderNumber' : IDL.Text,
    'returnType' : IDL.Variant({
      'full' : IDL.Null,
      'cancellation' : IDL.Null,
      'partial' : IDL.Null,
    }),
    'otherReason' : IDL.Opt(IDL.Text),
    'reason' : IDL.Variant({
      'other' : IDL.Null,
      'defective' : IDL.Null,
      'incorrect' : IDL.Null,
      'change_of_mind' : IDL.Null,
    }),
  });
  const ReturnOrder = IDL.Record({
    'refundAmount' : IDL.Float64,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'processed' : IDL.Null,
    }),
    'originalOrderId' : IDL.Text,
    'stockRestored' : IDL.Bool,
    'createdDate' : IDL.Int,
    'items' : IDL.Vec(ReturnItem),
    'processedDate' : IDL.Opt(IDL.Int),
    'statusChangeNotes' : IDL.Opt(IDL.Text),
    'returnNumber' : IDL.Text,
    'adminNotes' : IDL.Text,
    'originalOrderNumber' : IDL.Text,
    'returnType' : IDL.Variant({
      'full' : IDL.Null,
      'cancellation' : IDL.Null,
      'partial' : IDL.Null,
    }),
    'returnId' : IDL.Nat,
    'otherReason' : IDL.Opt(IDL.Text),
    'reason' : IDL.Variant({
      'other' : IDL.Null,
      'defective' : IDL.Null,
      'incorrect' : IDL.Null,
      'change_of_mind' : IDL.Null,
    }),
  });
  const ReturnResult = IDL.Record({
    'returnOrder' : ReturnOrder,
    'warnings' : IDL.Vec(IDL.Text),
    'success' : IDL.Bool,
  });
  const CategoryExportDTO = IDL.Record({
    'id' : IDL.Nat,
    'defaultIVA' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'defaultProfitMargin' : IDL.Nat,
    'productCount' : IDL.Nat,
  });
  const CategoriesExportResult = IDL.Record({
    'categories' : IDL.Vec(CategoryExportDTO),
    'totalCount' : IDL.Nat,
    'exportTimestamp' : IDL.Text,
  });
  const TaxBreakdownExportDTO = IDL.Record({
    'taxableAmount' : IDL.Float64,
    'ivaRate' : IDL.Nat,
    'baseAmount' : IDL.Float64,
    'taxAmount' : IDL.Float64,
  });
  const OrderItemExportDTO = IDL.Record({
    'categoryName' : IDL.Text,
    'ivaRate' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'salePrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
    'productBarcode' : IDL.Text,
  });
  const OrderExportDTO = IDL.Record({
    'status' : IDL.Text,
    'customerNotes' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'discountAmount' : IDL.Float64,
    'orderId' : IDL.Text,
    'printReceipt' : IDL.Bool,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Text,
    'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdownExportDTO)),
    'items' : IDL.Vec(OrderItemExportDTO),
    'orderNumber' : IDL.Text,
  });
  const OrdersExportResult = IDL.Record({
    'orders' : IDL.Vec(OrderExportDTO),
    'totalCount' : IDL.Nat,
    'exportTimestamp' : IDL.Text,
  });
  const ProductExportDTO = IDL.Record({
    'iva' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'updatedDate' : IDL.Text,
    'name' : IDL.Text,
    'createdDate' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'salePrice' : IDL.Float64,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
  });
  const ProductsExportResult = IDL.Record({
    'totalCount' : IDL.Nat,
    'products' : IDL.Vec(ProductExportDTO),
    'exportTimestamp' : IDL.Text,
  });
  const ReceiptData = IDL.Record({
    'order' : IDL.Opt(Order),
    'receiptType' : IDL.Variant({
      'order' : IDL.Null,
      'returnOrder' : IDL.Null,
    }),
    'returnOrder' : IDL.Opt(ReturnOrder),
    'storeInfo' : IDL.Record({
      'name' : IDL.Text,
      'whatsapp' : IDL.Text,
      'address' : IDL.Text,
      'phone' : IDL.Text,
    }),
    'timestamp' : IDL.Int,
  });
  const ArchivePreviewResult = IDL.Record({ 'orderCount' : IDL.Nat });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'defaultIVA' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'defaultProfitMargin' : IDL.Nat,
  });
  const AnalyticsFilters = IDL.Record({
    'categoryFilter' : IDL.Opt(IDL.Nat),
    'paymentMethodFilter' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Int,
    'includeArchived' : IDL.Bool,
    'fromDate' : IDL.Int,
  });
  const AdjustmentAnalytics = IDL.Record({
    'totalValueLost' : IDL.Float64,
    'mostAffectedProduct' : IDL.Opt(
      IDL.Record({ 'name' : IDL.Text, 'amount' : IDL.Nat })
    ),
    'totalAdjustments' : IDL.Nat,
    'primaryReason' : IDL.Opt(IDL.Text),
  });
  const AdjustmentFilters = IDL.Record({
    'reasonFilter' : IDL.Opt(IDL.Text),
    'adjustmentTypeFilter' : IDL.Opt(IDL.Text),
    'toDate' : IDL.Opt(IDL.Int),
    'fromDate' : IDL.Opt(IDL.Int),
    'productSearch' : IDL.Opt(IDL.Text),
  });
  const PaginatedAdjustments = IDL.Record({
    'totalCount' : IDL.Nat,
    'adjustments' : IDL.Vec(InventoryAdjustment),
  });
  const ArchivedOrder = IDL.Record({
    'order' : Order,
    'archiveDate' : IDL.Int,
  });
  const PaginatedArchivedOrders = IDL.Record({
    'orders' : IDL.Vec(ArchivedOrder),
    'totalCount' : IDL.Nat,
  });
  const PaginatedOrders = IDL.Record({
    'orders' : IDL.Vec(Order),
    'totalCount' : IDL.Nat,
  });
  const ProductWithCategory = IDL.Record({
    'categoryName' : IDL.Text,
    'product' : Product,
  });
  const PaginatedProducts = IDL.Record({
    'totalCount' : IDL.Nat,
    'products' : IDL.Vec(ProductWithCategory),
  });
  const PaginatedReturns = IDL.Record({
    'totalCount' : IDL.Nat,
    'returns' : IDL.Vec(ReturnOrder),
  });
  const AnalyticsData = IDL.Record({
    'archivedOrders' : IDL.Vec(Order),
    'activeOrders' : IDL.Vec(Order),
  });
  const StoreDetails = IDL.Record({
    'taxId' : IDL.Opt(IDL.Text),
    'lastUpdated' : IDL.Int,
    'whatsapp' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'storeName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CategoryImportDTO = IDL.Record({
    'categoryId' : IDL.Nat,
    'defaultIVA' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'defaultProfitMargin' : IDL.Nat,
  });
  const CategoriesImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'importedCount' : IDL.Nat,
    'errorCount' : IDL.Nat,
    'skippedCount' : IDL.Nat,
  });
  const LegacyCategoryImportDTO = IDL.Record({
    'defaultIVA' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'defaultProfitMargin' : IDL.Nat,
  });
  const ImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'successCount' : IDL.Nat,
    'errorCount' : IDL.Nat,
  });
  const LegacyProductImportDTO = IDL.Record({
    'categoryName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'salePrice' : IDL.Float64,
  });
  const TaxBreakdownImportDTO = IDL.Record({
    'taxableAmount' : IDL.Float64,
    'ivaRate' : IDL.Nat,
    'baseAmount' : IDL.Float64,
    'taxAmount' : IDL.Float64,
  });
  const OrderItemImportDTO = IDL.Record({
    'categoryName' : IDL.Text,
    'ivaRate' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'salePrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
    'productBarcode' : IDL.Text,
    'updatedStock' : IDL.Nat,
    'originalStock' : IDL.Nat,
  });
  const OrderImportDTO = IDL.Record({
    'status' : IDL.Text,
    'customerNotes' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'discountAmount' : IDL.Float64,
    'orderId' : IDL.Text,
    'printReceipt' : IDL.Bool,
    'totalAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
    'taxBreakdown' : IDL.Opt(IDL.Vec(TaxBreakdownImportDTO)),
    'items' : IDL.Vec(OrderItemImportDTO),
    'orderNumber' : IDL.Text,
  });
  const OrderImportConfig = IDL.Record({
    'targetDataset' : IDL.Text,
    'preserveTimestamps' : IDL.Bool,
    'updateStock' : IDL.Bool,
    'conflictResolution' : IDL.Text,
  });
  const OrdersImportResult = IDL.Record({
    'resultDetails' : IDL.Vec(IDL.Text),
    'nextOrderId' : IDL.Nat,
    'errors' : IDL.Vec(IDL.Text),
    'importedCount' : IDL.Nat,
    'updatedCount' : IDL.Nat,
    'errorCount' : IDL.Nat,
    'skippedCount' : IDL.Nat,
  });
  const ProductImportDTO = IDL.Record({
    'iva' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'updatedDate' : IDL.Int,
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
  });
  const ProductsImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Text),
    'importedCount' : IDL.Nat,
    'errorCount' : IDL.Nat,
    'skippedCount' : IDL.Nat,
  });
  const ProductSearchResult = IDL.Record({
    'iva' : IDL.Nat,
    'categoryName' : IDL.Text,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
    'profitMargin' : IDL.Nat,
    'basePrice' : IDL.Float64,
  });
  const StatusResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    'addCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func([Product], [], []),
    'archiveOrders' : IDL.Func([IDL.Int, IDL.Int], [ArchiveResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCallerUserRoleByText' : IDL.Func([IDL.Text, UserRole], [], []),
    'bulkUpdateCategories' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)))],
        [],
        [],
      ),
    'bulkUpdateProductsByCategory' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'createInventoryAdjustment' : IDL.Func(
        [AdjustmentDTO],
        [AdjustmentResult],
        [],
      ),
    'createOrder' : IDL.Func([CreateOrderRequest], [CreateOrderResponse], []),
    'createReturn' : IDL.Func([ReturnOrderDTO], [ReturnResult], []),
    'deleteCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'exportCategories' : IDL.Func([], [CategoriesExportResult], ['query']),
    'exportOrders' : IDL.Func(
        [
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [OrdersExportResult],
        ['query'],
      ),
    'exportProducts' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
        ],
        [ProductsExportResult],
        ['query'],
      ),
    'generateReturnReceipt' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ReceiptData)],
        ['query'],
      ),
    'getArchivePreview' : IDL.Func(
        [IDL.Int, IDL.Int],
        [ArchivePreviewResult],
        ['query'],
      ),
    'getArchivedOrderDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Order)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getInventoryAdjustmentAnalytics' : IDL.Func(
        [AnalyticsFilters],
        [AdjustmentAnalytics],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPaginatedAdjustments' : IDL.Func(
        [IDL.Nat, IDL.Nat, AdjustmentFilters],
        [PaginatedAdjustments],
        ['query'],
      ),
    'getPaginatedArchivedOrders' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
        ],
        [PaginatedArchivedOrders],
        ['query'],
      ),
    'getPaginatedOrders' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [PaginatedOrders],
        ['query'],
      ),
    'getPaginatedProducts' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [PaginatedProducts],
        ['query'],
      ),
    'getPaginatedReturns' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [PaginatedReturns],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getReturnDetails' : IDL.Func([IDL.Nat], [IDL.Opt(ReturnOrder)], ['query']),
    'getSalesAnalyticsData' : IDL.Func(
        [AnalyticsFilters],
        [AnalyticsData],
        ['query'],
      ),
    'getStoreDetails' : IDL.Func([], [StoreDetails], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importCategories' : IDL.Func(
        [IDL.Vec(CategoryImportDTO)],
        [CategoriesImportResult],
        [],
      ),
    'importLegacyCategories' : IDL.Func(
        [IDL.Vec(LegacyCategoryImportDTO)],
        [ImportResult],
        [],
      ),
    'importLegacyProducts' : IDL.Func(
        [IDL.Vec(LegacyProductImportDTO)],
        [ImportResult],
        [],
      ),
    'importOrders' : IDL.Func(
        [IDL.Vec(OrderImportDTO), OrderImportConfig],
        [OrdersImportResult],
        [],
      ),
    'importProducts' : IDL.Func(
        [IDL.Vec(ProductImportDTO)],
        [ProductsImportResult],
        [],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProductsForCheckout' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(ProductSearchResult)],
        ['query'],
      ),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateReturnStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'rejected' : IDL.Null,
            'processed' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [StatusResult],
        [],
      ),
    'updateStoreDetails' : IDL.Func(
        [StoreDetails],
        [IDL.Record({ 'message' : IDL.Text, 'success' : IDL.Bool })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };