/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdjustmentAnalytics {
  'totalValueLost' : number,
  'mostAffectedProduct' : [] | [{ 'name' : string, 'amount' : bigint }],
  'totalAdjustments' : bigint,
  'primaryReason' : [] | [string],
}
export interface AdjustmentDTO {
  'dateEffective' : bigint,
  'quantity' : bigint,
  'adjustmentType' : { 'decrease' : null } |
    { 'increase' : null },
  'adminNotes' : string,
  'productBarcode' : string,
  'reason' : { 'theft' : null } |
    { 'broken' : null } |
    { 'expired' : null } |
    { 'lost' : null } |
    { 'count' : null } |
    { 'error' : null },
}
export interface AdjustmentFilters {
  'reasonFilter' : [] | [string],
  'adjustmentTypeFilter' : [] | [string],
  'toDate' : [] | [bigint],
  'fromDate' : [] | [bigint],
  'productSearch' : [] | [string],
}
export interface AdjustmentResult {
  'adjustment' : InventoryAdjustment,
  'warnings' : Array<string>,
  'success' : boolean,
}
export interface AnalyticsData {
  'archivedOrders' : Array<Order>,
  'activeOrders' : Array<Order>,
}
export interface AnalyticsFilters {
  'categoryFilter' : [] | [bigint],
  'paymentMethodFilter' : [] | [string],
  'toDate' : bigint,
  'includeArchived' : boolean,
  'fromDate' : bigint,
}
export interface ArchivePreviewResult { 'orderCount' : bigint }
export interface ArchiveResult {
  'archivedCount' : bigint,
  'archivedIds' : Array<string>,
}
export interface ArchivedOrder { 'order' : Order, 'archiveDate' : bigint }
export interface CategoriesExportResult {
  'categories' : Array<CategoryExportDTO>,
  'totalCount' : bigint,
  'exportTimestamp' : string,
}
export interface CategoriesImportResult {
  'errors' : Array<string>,
  'importedCount' : bigint,
  'errorCount' : bigint,
  'skippedCount' : bigint,
}
export interface Category {
  'id' : bigint,
  'defaultIVA' : bigint,
  'order' : bigint,
  'name' : string,
  'defaultProfitMargin' : bigint,
}
export interface CategoryExportDTO {
  'id' : bigint,
  'defaultIVA' : bigint,
  'order' : bigint,
  'name' : string,
  'defaultProfitMargin' : bigint,
  'productCount' : bigint,
}
export interface CategoryImportDTO {
  'categoryId' : bigint,
  'defaultIVA' : bigint,
  'order' : bigint,
  'name' : string,
  'defaultProfitMargin' : bigint,
}
export interface CreateOrderRequest {
  'customerName' : [] | [string],
  'customerNotes' : string,
  'paymentMethod' : { 'card' : null } |
    { 'cash' : null } |
    { 'transfer' : null },
  'discountAmount' : number,
  'customerTaxId' : [] | [string],
  'invoiceType' : string,
  'printReceipt' : boolean,
  'taxBreakdown' : [] | [Array<TaxBreakdown>],
  'items' : Array<OrderItem>,
}
export interface CreateOrderResponse {
  'order' : Order,
  'warnings' : Array<string>,
  'success' : boolean,
}
export interface ImportResult {
  'errors' : Array<string>,
  'successCount' : bigint,
  'errorCount' : bigint,
}
export interface InventoryAdjustment {
  'dateEffective' : bigint,
  'productName' : string,
  'adminUserId' : string,
  'timestamp' : bigint,
  'newStock' : bigint,
  'previousStock' : bigint,
  'quantity' : bigint,
  'adjustmentId' : bigint,
  'adjustmentType' : { 'decrease' : null } |
    { 'increase' : null },
  'adminNotes' : string,
  'productBarcode' : string,
  'reason' : { 'theft' : null } |
    { 'broken' : null } |
    { 'expired' : null } |
    { 'lost' : null } |
    { 'count' : null } |
    { 'error' : null },
}
export interface LegacyCategoryImportDTO {
  'defaultIVA' : bigint,
  'order' : bigint,
  'name' : string,
  'defaultProfitMargin' : bigint,
}
export interface LegacyProductImportDTO {
  'categoryName' : string,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'barcode' : string,
  'salePrice' : number,
}
export interface Order {
  'customerName' : [] | [string],
  'status' : { 'valid' : null } |
    { 'invalid' : null },
  'customerNotes' : string,
  'paymentMethod' : { 'card' : null } |
    { 'cash' : null } |
    { 'transfer' : null },
  'discountAmount' : number,
  'orderId' : string,
  'customerTaxId' : [] | [string],
  'invoiceType' : string,
  'printReceipt' : boolean,
  'totalAmount' : number,
  'timestamp' : bigint,
  'taxBreakdown' : [] | [Array<TaxBreakdown>],
  'items' : Array<OrderItem>,
  'orderNumber' : string,
}
export interface OrderExportDTO {
  'status' : string,
  'customerNotes' : string,
  'paymentMethod' : string,
  'discountAmount' : number,
  'orderId' : string,
  'printReceipt' : boolean,
  'totalAmount' : number,
  'timestamp' : string,
  'taxBreakdown' : [] | [Array<TaxBreakdownExportDTO>],
  'items' : Array<OrderItemExportDTO>,
  'orderNumber' : string,
}
export interface OrderImportConfig {
  'targetDataset' : string,
  'preserveTimestamps' : boolean,
  'updateStock' : boolean,
  'conflictResolution' : string,
}
export interface OrderImportDTO {
  'status' : string,
  'customerNotes' : string,
  'paymentMethod' : string,
  'discountAmount' : number,
  'orderId' : string,
  'printReceipt' : boolean,
  'totalAmount' : number,
  'timestamp' : bigint,
  'taxBreakdown' : [] | [Array<TaxBreakdownImportDTO>],
  'items' : Array<OrderItemImportDTO>,
  'orderNumber' : string,
}
export interface OrderItem {
  'categoryName' : string,
  'ivaRate' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'salePrice' : number,
  'totalPrice' : number,
  'profitMargin' : bigint,
  'basePrice' : number,
  'productBarcode' : string,
  'updatedStock' : bigint,
  'originalStock' : bigint,
}
export interface OrderItemExportDTO {
  'categoryName' : string,
  'ivaRate' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'salePrice' : number,
  'totalPrice' : number,
  'profitMargin' : bigint,
  'basePrice' : number,
  'productBarcode' : string,
}
export interface OrderItemImportDTO {
  'categoryName' : string,
  'ivaRate' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'salePrice' : number,
  'totalPrice' : number,
  'profitMargin' : bigint,
  'basePrice' : number,
  'productBarcode' : string,
  'updatedStock' : bigint,
  'originalStock' : bigint,
}
export interface OrdersExportResult {
  'orders' : Array<OrderExportDTO>,
  'totalCount' : bigint,
  'exportTimestamp' : string,
}
export interface OrdersImportResult {
  'resultDetails' : Array<string>,
  'nextOrderId' : bigint,
  'errors' : Array<string>,
  'importedCount' : bigint,
  'updatedCount' : bigint,
  'errorCount' : bigint,
  'skippedCount' : bigint,
}
export interface PaginatedAdjustments {
  'totalCount' : bigint,
  'adjustments' : Array<InventoryAdjustment>,
}
export interface PaginatedArchivedOrders {
  'orders' : Array<ArchivedOrder>,
  'totalCount' : bigint,
}
export interface PaginatedOrders {
  'orders' : Array<Order>,
  'totalCount' : bigint,
}
export interface PaginatedProducts {
  'totalCount' : bigint,
  'products' : Array<ProductWithCategory>,
}
export interface PaginatedReturns {
  'totalCount' : bigint,
  'returns' : Array<ReturnOrder>,
}
export interface Product {
  'iva' : bigint,
  'categoryId' : bigint,
  'updatedDate' : bigint,
  'name' : string,
  'createdDate' : bigint,
  'description' : string,
  'stock' : bigint,
  'barcode' : string,
  'profitMargin' : bigint,
  'basePrice' : number,
}
export interface ProductExportDTO {
  'iva' : bigint,
  'categoryId' : bigint,
  'updatedDate' : string,
  'name' : string,
  'createdDate' : string,
  'description' : string,
  'stock' : bigint,
  'barcode' : string,
  'salePrice' : number,
  'profitMargin' : bigint,
  'basePrice' : number,
}
export interface ProductImportDTO {
  'iva' : bigint,
  'categoryId' : bigint,
  'updatedDate' : bigint,
  'name' : string,
  'createdDate' : bigint,
  'description' : string,
  'stock' : bigint,
  'barcode' : string,
  'profitMargin' : bigint,
  'basePrice' : number,
}
export interface ProductSearchResult {
  'iva' : bigint,
  'categoryName' : string,
  'name' : string,
  'stock' : bigint,
  'barcode' : string,
  'profitMargin' : bigint,
  'basePrice' : number,
}
export interface ProductWithCategory {
  'categoryName' : string,
  'product' : Product,
}
export interface ProductsExportResult {
  'totalCount' : bigint,
  'products' : Array<ProductExportDTO>,
  'exportTimestamp' : string,
}
export interface ProductsImportResult {
  'errors' : Array<string>,
  'importedCount' : bigint,
  'errorCount' : bigint,
  'skippedCount' : bigint,
}
export interface ReceiptData {
  'order' : [] | [Order],
  'receiptType' : { 'order' : null } |
    { 'returnOrder' : null },
  'returnOrder' : [] | [ReturnOrder],
  'storeInfo' : {
    'name' : string,
    'whatsapp' : string,
    'address' : string,
    'phone' : string,
  },
  'timestamp' : bigint,
}
export interface ReturnItem {
  'returnedQuantity' : bigint,
  'categoryName' : string,
  'stockRestored' : boolean,
  'originalQuantity' : bigint,
  'productName' : string,
  'refundPerUnit' : number,
  'totalRefund' : number,
  'productBarcode' : string,
}
export interface ReturnOrder {
  'refundAmount' : number,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'processed' : null },
  'originalOrderId' : string,
  'stockRestored' : boolean,
  'createdDate' : bigint,
  'items' : Array<ReturnItem>,
  'processedDate' : [] | [bigint],
  'statusChangeNotes' : [] | [string],
  'returnNumber' : string,
  'adminNotes' : string,
  'originalOrderNumber' : string,
  'returnType' : { 'full' : null } |
    { 'cancellation' : null } |
    { 'partial' : null },
  'returnId' : bigint,
  'otherReason' : [] | [string],
  'reason' : { 'other' : null } |
    { 'defective' : null } |
    { 'incorrect' : null } |
    { 'change_of_mind' : null },
}
export interface ReturnOrderDTO {
  'refundAmount' : number,
  'originalOrderId' : string,
  'items' : Array<ReturnItem>,
  'adminNotes' : string,
  'originalOrderNumber' : string,
  'returnType' : { 'full' : null } |
    { 'cancellation' : null } |
    { 'partial' : null },
  'otherReason' : [] | [string],
  'reason' : { 'other' : null } |
    { 'defective' : null } |
    { 'incorrect' : null } |
    { 'change_of_mind' : null },
}
export interface ReturnResult {
  'returnOrder' : ReturnOrder,
  'warnings' : Array<string>,
  'success' : boolean,
}
export interface StatusResult { 'message' : string, 'success' : boolean }
export interface StoreDetails {
  'taxId' : [] | [string],
  'lastUpdated' : bigint,
  'whatsapp' : string,
  'email' : [] | [string],
  'website' : [] | [string],
  'address' : string,
  'storeName' : string,
  'phone' : string,
}
export interface TaxBreakdown {
  'taxableAmount' : number,
  'ivaRate' : bigint,
  'baseAmount' : number,
  'taxAmount' : number,
}
export interface TaxBreakdownExportDTO {
  'taxableAmount' : number,
  'ivaRate' : bigint,
  'baseAmount' : number,
  'taxAmount' : number,
}
export interface TaxBreakdownImportDTO {
  'taxableAmount' : number,
  'ivaRate' : bigint,
  'baseAmount' : number,
  'taxAmount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addCategory' : ActorMethod<[string, bigint, bigint, bigint], bigint>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'archiveOrders' : ActorMethod<[bigint, bigint], ArchiveResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCallerUserRoleByText' : ActorMethod<[string, UserRole], undefined>,
  'bulkUpdateCategories' : ActorMethod<
    [Array<[bigint, [] | [bigint], [] | [bigint]]>],
    undefined
  >,
  'bulkUpdateProductsByCategory' : ActorMethod<
    [bigint, bigint, bigint],
    undefined
  >,
  'createInventoryAdjustment' : ActorMethod<[AdjustmentDTO], AdjustmentResult>,
  'createOrder' : ActorMethod<[CreateOrderRequest], CreateOrderResponse>,
  'createReturn' : ActorMethod<[ReturnOrderDTO], ReturnResult>,
  'deleteCategory' : ActorMethod<[bigint, string], undefined>,
  'deleteProduct' : ActorMethod<[string, string], undefined>,
  'exportCategories' : ActorMethod<[], CategoriesExportResult>,
  'exportOrders' : ActorMethod<
    [[] | [bigint], [] | [bigint], [] | [string], [] | [string]],
    OrdersExportResult
  >,
  'exportProducts' : ActorMethod<
    [[] | [bigint], [] | [bigint], [] | [bigint], [] | [bigint], [] | [bigint]],
    ProductsExportResult
  >,
  'generateReturnReceipt' : ActorMethod<[bigint], [] | [ReceiptData]>,
  'getArchivePreview' : ActorMethod<[bigint, bigint], ArchivePreviewResult>,
  'getArchivedOrderDetails' : ActorMethod<[string], [] | [Order]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getInventoryAdjustmentAnalytics' : ActorMethod<
    [AnalyticsFilters],
    AdjustmentAnalytics
  >,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPaginatedAdjustments' : ActorMethod<
    [bigint, bigint, AdjustmentFilters],
    PaginatedAdjustments
  >,
  'getPaginatedArchivedOrders' : ActorMethod<
    [bigint, bigint, string, string, [] | [bigint], [] | [bigint]],
    PaginatedArchivedOrders
  >,
  'getPaginatedOrders' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      [] | [bigint],
      [] | [bigint],
      [] | [string],
    ],
    PaginatedOrders
  >,
  'getPaginatedProducts' : ActorMethod<
    [bigint, bigint, string, string, bigint, [] | [bigint], [] | [bigint]],
    PaginatedProducts
  >,
  'getPaginatedReturns' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      [] | [bigint],
      [] | [bigint],
      [] | [string],
    ],
    PaginatedReturns
  >,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getReturnDetails' : ActorMethod<[bigint], [] | [ReturnOrder]>,
  'getSalesAnalyticsData' : ActorMethod<[AnalyticsFilters], AnalyticsData>,
  'getStoreDetails' : ActorMethod<[], StoreDetails>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importCategories' : ActorMethod<
    [Array<CategoryImportDTO>],
    CategoriesImportResult
  >,
  'importLegacyCategories' : ActorMethod<
    [Array<LegacyCategoryImportDTO>],
    ImportResult
  >,
  'importLegacyProducts' : ActorMethod<
    [Array<LegacyProductImportDTO>],
    ImportResult
  >,
  'importOrders' : ActorMethod<
    [Array<OrderImportDTO>, OrderImportConfig],
    OrdersImportResult
  >,
  'importProducts' : ActorMethod<
    [Array<ProductImportDTO>],
    ProductsImportResult
  >,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProductsForCheckout' : ActorMethod<
    [string, string, bigint],
    Array<ProductSearchResult>
  >,
  'updateCategory' : ActorMethod<
    [bigint, string, bigint, bigint, bigint],
    undefined
  >,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateReturnStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'rejected' : null } |
        { 'processed' : null },
      [] | [string],
    ],
    StatusResult
  >,
  'updateStoreDetails' : ActorMethod<
    [StoreDetails],
    { 'message' : string, 'success' : boolean }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];